### ISSUE TITLE
wishlist

### ISSUE THREAD

**Issue by aayanl** [ZencashOfficial/zencash-mobile#2]
Note I'm basing this of https://samouraiwallet.com/ which is an awesome bitcoin wallet
***

* Option to use Tor via https://play.google.com/store/apps/details?id=org.torproject.android&hl=en
* Option to choose your own Insight API
* * When secure nodes go live, option to choose your own secure node
* Automatic fee rates
* * Insight already offers this: https://github.com/aayanl/insight-api-zen#utility-methods
* Require user to input a pin to use when launching the wallet
* Warn user if their phone is rooted/jailbroken that any app can access wallet info if necessary precautions aren't taken.

**Comment by alexanderzabuga** [comment]
There's quite a lot of unused space on a page with QR code & address. Not that it's a bad thing however I've been thinking how to properly use it. I think since by nature lots of people will have lots of different zen addresses, it would be great if there was some text-message / memo we could attach to it? For example I'm a landlord, if I were to accept payments in zen I'd make a new zen address for that and it would be different from my main address just to keep track of it and it would be great if I could distinguish them locally by my own written memos.
Same goes for transactions. Click on transaction, prompt to write a quick memo what this transaction was about (probably will conflict with default zen's messaging. we have to wait and see how network develops. if it becomes a norm to attach a message with your transaction we could display that instead).

**Comment by kendricktan** [comment]
@alexanderzabuga definitely, there's actually been a couple of new releases, and the UI has changed significantly since v0.0.1a. Try out v0.0.4a (coming out soon), and tell me what you think (in terms of the UI). As for the memo, its not possible unless you're doing a private transaction, which isn't supported at this point in time.

**Comment by zennermac** [comment]
Hi there

Sphere By Horizen for Android is on plan to replace zencash-mobile in the coming months
As such we will not be making any major updates to this wallet.

Regards
