### ISSUE TITLE
error message when sending zen

### ISSUE THREAD

**Issue by oroszms** [ZencashOfficial/zencash-mobile#45]
Since the update to 0.0.6 I get an error message trying to send ZEN. Tried to change the fee, refresh the max amount, recover the wallet without luck. It was working well before, I have made couple of transactions without problems.

**Comment by kendricktan** [comment]
@oroszms 
Can I have your Android Version and what kind of error message is it throwing?

**Comment by oroszms** [comment]
Hi! Sure. Android 6.0.1 (Samsung A9 Pro - A910F). Here is the error message, hope it appears: (https://ibin.co/3ehjyQOF48Bd.png). Since I managed to make the transfer on the version 0.0.4a from the github releases.

**Comment by kendricktan** [comment]
I'm sorry to hear that, I'll be working on that

In the meantime you can downgrade to v0.0.5: https://github.com/ZencashOfficial/zencash-mobile/releases/tag/v0.0.5

**Comment by oroszms** [comment]
Thanks for quick reply and making the apk available. Sorry, I cannot test more as I have managed to.transfer my ZENs out. I am not 100% sure, but I think the progress bar was making to the end.

**Comment by kendricktan** [comment]
Always here to help! :smile:

**Comment by kendricktan** [comment]
So it turns out that *.zensystem.io updated their certificates. The reason there was a 400 error was probably because the wallet was using a cached version of the cerificate. Clear the cache and data of the app to fix this issue. **(Back up your secret phrase first, you WILL lose it upon clearing the cache and data)**
