### ISSUE TITLE
send zen error

### ISSUE THREAD

**Issue by yak10** [ZencashOfficial/zencash-mobile#59]
I cannot send Zen

**Comment by tross2015** [comment]
I am having same issue. Otherwise its a very nice wallet and a very good job was done!

**Comment by kendricktan** [comment]
Hey there's, what error code are you getting?

**Comment by kendricktan** [comment]
Also have you tried changing your insight node to another node on settings -> insight api ?

**Comment by tross2015** [comment]
Tried changing all 4 api and tried 1 time manual
History
received 11 nov  ok
sent  19 Nov   ok
received 29 Nov ok
send 29 Nov  error

**Comment by kendricktan** [comment]
Hi sorry you're having issue, can you screenshot the error code?
In the meantime you can try downloading the older releases: https://github.com/ZencashOfficial/zencash-mobile/releases

Or import your private key to the swing wallet.

**Comment by yak10** [comment]
error send

**Comment by tross2015** [comment]
I could wait but will this issue be fixed? so something changed in the 10 days before 29 Nov 17

**Comment by kendricktan** [comment]
Can you try using the latest version? https://github.com/ZencashOfficial/zencash-mobile/releases/tag/v0.0.12 @yak10

**Comment by tross2015** [comment]
I am using 0.0.11. Maybe it showed error cause I picked max withdraw. Cause when I made it 5 instead of 5.25 it worked fine. Maybe it dont like decimal point. 

Gesendet von Yahoo Mail auf Android 
 
  Am Fr., Dez. 1, 2017 at 11:31 PM schrieb Kendrick Tan<notifications@github.com>:   
Can you try using the latest version? https://github.com/ZencashOfficial/zencash-mobile/releases/tag/v0.0.12 @yak10

**Comment by kendricktan** [comment]
@tross2015 try v0.0.12

**Comment by tross2015** [comment]
I give it a go thanks!

**Comment by tross2015** [comment]
| 0.25418644 was sent to cryptopia! Thanks for the fix!
-- | --

**Comment by yak10** [comment]
Tq for support
