### ISSUE TITLE
Backup phrase

### ISSUE THREAD

**Issue by oakmaster** [ZencashOfficial/zencash-mobile#7]
This is awesome that Zen finally has a mobile wallet I just have 2 things is there a way we can see the backup phrase in English also I no you just started this but in the future could you add finger scanner support in security settings that would really be cool and there's not any mobile wallets yet I think with that support finger scanner that would really separate this wallet from the rest

**Comment by kendricktan** [comment]
@oakmaster the backup phrase is just a set of randomly generated characters, it isn't in any specific language. If you would like to generate a wallet based on a phrase of words, I suggest you click on `recover an existing wallet` and enter in your secret phrase there.

As for the finger print, probably not anytime soon because not alot of devices support it. But PIN codes will be out in the following (or so) releases. :+1:
