### ISSUE TITLE
0.000 value for btc and usd

### ISSUE THREAD

**Issue by Gabkicks** [ZencashOfficial/zencash-mobile#96]
My zen wallet shows 0.0000 value for USD and BTC even though the wallet isn't empty
 I have version 0.0.16.

**Comment by fredostr** [comment]
Same error, same version

**Comment by Sto1cNate** [comment]
@Gabkicks @fredostr This is a known issue with existing pricing API. We're migrating ATM to a new mechanism. Releases will be announced/published in the usual channels.

**Comment by aliraza61946** [comment]
My zen wallet shows 0.0000 value for USD and BTC even though the wallet isn't empty
I have version 0.0.16.

**Comment by uanl979** [comment]
hey @aliraza61946 @Gabkicks 

It's a deprecated price API issue causing to reflect 0 USD and BTC. Nevertheless your address still contains the ZEN that the app mentions. No need to worry on this.

This is targeted to be fixed in the near future. 

Will keep our community posted when this issue get fixed.

Regards
