### ISSUE TITLE
wallet show no connection

### ISSUE THREAD

**Issue by sonumehto0** [ZencashOfficial/zencash-mobile#99]
my internet on but app show no connection. so i clear data storage and open again wallet open new adress my wallet is not recovering.now its show zero zen.how to recover it.
![Screenshot_20200423-055341](https://user-images.githubusercontent.com/64175940/80046686-f000ed00-8528-11ea-9d29-aea15f46beab.jpg)
![Screenshot_20200423-061025](https://user-images.githubusercontent.com/64175940/80046773-33f3f200-8529-11ea-9720-503eb5d09522.jpg)

**Comment by uanl979** [comment]
hey @sonumehto0 

1. Were you having connectivity issues?
2. Deleting app's data will erase you wallet info, that's why you are experimenting this issue.
3. Is the restoring process, restoring the same addresses you previously had?

Would like to provide you further support through our helpdesk, do you mind if I create a ticket on your behalf? I just need your email account. 

Regards
Rubén

**Comment by aliraza61946** [comment]
Hello mu name is ali raza. My zen wallet show no connection 
Plz solve this 
Thank u so much

**Comment by aliraza61946** [comment]
![Screenshot_20200430_211341](https://user-images.githubusercontent.com/64302261/80733765-918ace80-8b27-11ea-85cf-a76fba767709.jpg)
This issue

**Comment by uanl979** [comment]
@aliraza61946 

Would like to provide you further support through our helpdesk, do you mind if I create a ticket on your behalf? I just need your email account.

Regards
Rubén

**Comment by aliraza61946** [comment]
Aliraza61946@gmail.com

**Comment by uanl979** [comment]
I will be closing this issue since @aliraza61946's issue has been moved to helpdesk.

@sonumehto0, please raise a suppor ticket if you need further assistance. 

[Helpdesk](https://horizenofficial.atlassian.net/servicedesk/customer/portals)
